// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: datax-sdk-protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_sdk_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_datax_sdk_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_datax_sdk_protocol_proto_rawDescGZIP(), []int{0}
}

type Initialization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Initialization) Reset() {
	*x = Initialization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_sdk_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Initialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialization) ProtoMessage() {}

func (x *Initialization) ProtoReflect() protoreflect.Message {
	mi := &file_datax_sdk_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialization.ProtoReflect.Descriptor instead.
func (*Initialization) Descriptor() ([]byte, []int) {
	return file_datax_sdk_protocol_proto_rawDescGZIP(), []int{1}
}

type NextOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NextOptions) Reset() {
	*x = NextOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_sdk_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextOptions) ProtoMessage() {}

func (x *NextOptions) ProtoReflect() protoreflect.Message {
	mi := &file_datax_sdk_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextOptions.ProtoReflect.Descriptor instead.
func (*NextOptions) Descriptor() ([]byte, []int) {
	return file_datax_sdk_protocol_proto_rawDescGZIP(), []int{2}
}

type NextMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference *string          `protobuf:"bytes,1,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
	Stream    *string          `protobuf:"bytes,2,opt,name=stream,proto3,oneof" json:"stream,omitempty"`
	Message   *structpb.Struct `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *NextMessage) Reset() {
	*x = NextMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_sdk_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextMessage) ProtoMessage() {}

func (x *NextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_datax_sdk_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextMessage.ProtoReflect.Descriptor instead.
func (*NextMessage) Descriptor() ([]byte, []int) {
	return file_datax_sdk_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *NextMessage) GetReference() string {
	if x != nil && x.Reference != nil {
		return *x.Reference
	}
	return ""
}

func (x *NextMessage) GetStream() string {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return ""
}

func (x *NextMessage) GetMessage() *structpb.Struct {
	if x != nil {
		return x.Message
	}
	return nil
}

type EmitMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference *string          `protobuf:"bytes,1,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
	Message   *structpb.Struct `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *EmitMessage) Reset() {
	*x = EmitMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_sdk_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitMessage) ProtoMessage() {}

func (x *EmitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_datax_sdk_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitMessage.ProtoReflect.Descriptor instead.
func (*EmitMessage) Descriptor() ([]byte, []int) {
	return file_datax_sdk_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *EmitMessage) GetReference() string {
	if x != nil && x.Reference != nil {
		return *x.Reference
	}
	return ""
}

func (x *EmitMessage) GetMessage() *structpb.Struct {
	if x != nil {
		return x.Message
	}
	return nil
}

type EmitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmitResult) Reset() {
	*x = EmitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datax_sdk_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResult) ProtoMessage() {}

func (x *EmitResult) ProtoReflect() protoreflect.Message {
	mi := &file_datax_sdk_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResult.ProtoReflect.Descriptor instead.
func (*EmitResult) Descriptor() ([]byte, []int) {
	return file_datax_sdk_protocol_proto_rawDescGZIP(), []int{5}
}

var File_datax_sdk_protocol_proto protoreflect.FileDescriptor

var file_datax_sdk_protocol_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0a, 0x0a, 0x08,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x65,
	0x78, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xaa, 0x01, 0x0a, 0x0b, 0x4e, 0x65,
	0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x09, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x48, 0x02, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x0b, 0x45, 0x6d, 0x69, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x48, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x45,
	0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xf0, 0x01, 0x0a, 0x05, 0x44, 0x61,
	0x74, 0x61, 0x58, 0x12, 0x50, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x12, 0x1c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x1a,
	0x22, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x04, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x1f, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1f,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x49, 0x0a, 0x04, 0x45, 0x6d, 0x69, 0x74, 0x12, 0x1f, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45,
	0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1e, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x45, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6c, 0x61, 0x2d, 0x69,
	0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datax_sdk_protocol_proto_rawDescOnce sync.Once
	file_datax_sdk_protocol_proto_rawDescData = file_datax_sdk_protocol_proto_rawDesc
)

func file_datax_sdk_protocol_proto_rawDescGZIP() []byte {
	file_datax_sdk_protocol_proto_rawDescOnce.Do(func() {
		file_datax_sdk_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_datax_sdk_protocol_proto_rawDescData)
	})
	return file_datax_sdk_protocol_proto_rawDescData
}

var file_datax_sdk_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_datax_sdk_protocol_proto_goTypes = []interface{}{
	(*Settings)(nil),        // 0: datax.sdk.protocol.Settings
	(*Initialization)(nil),  // 1: datax.sdk.protocol.Initialization
	(*NextOptions)(nil),     // 2: datax.sdk.protocol.NextOptions
	(*NextMessage)(nil),     // 3: datax.sdk.protocol.NextMessage
	(*EmitMessage)(nil),     // 4: datax.sdk.protocol.EmitMessage
	(*EmitResult)(nil),      // 5: datax.sdk.protocol.EmitResult
	(*structpb.Struct)(nil), // 6: google.protobuf.Struct
}
var file_datax_sdk_protocol_proto_depIdxs = []int32{
	6, // 0: datax.sdk.protocol.NextMessage.message:type_name -> google.protobuf.Struct
	6, // 1: datax.sdk.protocol.EmitMessage.message:type_name -> google.protobuf.Struct
	0, // 2: datax.sdk.protocol.DataX.Initialize:input_type -> datax.sdk.protocol.Settings
	2, // 3: datax.sdk.protocol.DataX.Next:input_type -> datax.sdk.protocol.NextOptions
	4, // 4: datax.sdk.protocol.DataX.Emit:input_type -> datax.sdk.protocol.EmitMessage
	1, // 5: datax.sdk.protocol.DataX.Initialize:output_type -> datax.sdk.protocol.Initialization
	3, // 6: datax.sdk.protocol.DataX.Next:output_type -> datax.sdk.protocol.NextMessage
	5, // 7: datax.sdk.protocol.DataX.Emit:output_type -> datax.sdk.protocol.EmitResult
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_datax_sdk_protocol_proto_init() }
func file_datax_sdk_protocol_proto_init() {
	if File_datax_sdk_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datax_sdk_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_sdk_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Initialization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_sdk_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_sdk_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_sdk_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datax_sdk_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_datax_sdk_protocol_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_datax_sdk_protocol_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datax_sdk_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datax_sdk_protocol_proto_goTypes,
		DependencyIndexes: file_datax_sdk_protocol_proto_depIdxs,
		MessageInfos:      file_datax_sdk_protocol_proto_msgTypes,
	}.Build()
	File_datax_sdk_protocol_proto = out.File
	file_datax_sdk_protocol_proto_rawDesc = nil
	file_datax_sdk_protocol_proto_goTypes = nil
	file_datax_sdk_protocol_proto_depIdxs = nil
}
