// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: v2/datax-sdk-protocol.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataXClient is the client API for DataX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataXClient interface {
	Initialize(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*Initialization, error)
	Next(ctx context.Context, in *NextOptions, opts ...grpc.CallOption) (*NextMessage, error)
	Emit(ctx context.Context, in *EmitMessage, opts ...grpc.CallOption) (*EmitResult, error)
	// Backend API
	GetRequest(ctx context.Context, in *GetRequestOptions, opts ...grpc.CallOption) (*Request, error)
	ReplyRequest(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*ReplyResult, error)
	// Backend client API
	SubmitRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type dataXClient struct {
	cc grpc.ClientConnInterface
}

func NewDataXClient(cc grpc.ClientConnInterface) DataXClient {
	return &dataXClient{cc}
}

func (c *dataXClient) Initialize(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*Initialization, error) {
	out := new(Initialization)
	err := c.cc.Invoke(ctx, "/datax.sdk.protocol.v2.DataX/Initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataXClient) Next(ctx context.Context, in *NextOptions, opts ...grpc.CallOption) (*NextMessage, error) {
	out := new(NextMessage)
	err := c.cc.Invoke(ctx, "/datax.sdk.protocol.v2.DataX/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataXClient) Emit(ctx context.Context, in *EmitMessage, opts ...grpc.CallOption) (*EmitResult, error) {
	out := new(EmitResult)
	err := c.cc.Invoke(ctx, "/datax.sdk.protocol.v2.DataX/Emit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataXClient) GetRequest(ctx context.Context, in *GetRequestOptions, opts ...grpc.CallOption) (*Request, error) {
	out := new(Request)
	err := c.cc.Invoke(ctx, "/datax.sdk.protocol.v2.DataX/GetRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataXClient) ReplyRequest(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*ReplyResult, error) {
	out := new(ReplyResult)
	err := c.cc.Invoke(ctx, "/datax.sdk.protocol.v2.DataX/ReplyRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataXClient) SubmitRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/datax.sdk.protocol.v2.DataX/SubmitRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataXServer is the server API for DataX service.
// All implementations must embed UnimplementedDataXServer
// for forward compatibility
type DataXServer interface {
	Initialize(context.Context, *Settings) (*Initialization, error)
	Next(context.Context, *NextOptions) (*NextMessage, error)
	Emit(context.Context, *EmitMessage) (*EmitResult, error)
	// Backend API
	GetRequest(context.Context, *GetRequestOptions) (*Request, error)
	ReplyRequest(context.Context, *Reply) (*ReplyResult, error)
	// Backend client API
	SubmitRequest(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedDataXServer()
}

// UnimplementedDataXServer must be embedded to have forward compatible implementations.
type UnimplementedDataXServer struct {
}

func (UnimplementedDataXServer) Initialize(context.Context, *Settings) (*Initialization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDataXServer) Next(context.Context, *NextOptions) (*NextMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedDataXServer) Emit(context.Context, *EmitMessage) (*EmitResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedDataXServer) GetRequest(context.Context, *GetRequestOptions) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedDataXServer) ReplyRequest(context.Context, *Reply) (*ReplyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyRequest not implemented")
}
func (UnimplementedDataXServer) SubmitRequest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRequest not implemented")
}
func (UnimplementedDataXServer) mustEmbedUnimplementedDataXServer() {}

// UnsafeDataXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataXServer will
// result in compilation errors.
type UnsafeDataXServer interface {
	mustEmbedUnimplementedDataXServer()
}

func RegisterDataXServer(s grpc.ServiceRegistrar, srv DataXServer) {
	s.RegisterService(&DataX_ServiceDesc, srv)
}

func _DataX_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataXServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datax.sdk.protocol.v2.DataX/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataXServer).Initialize(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataX_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataXServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datax.sdk.protocol.v2.DataX/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataXServer).Next(ctx, req.(*NextOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataX_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataXServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datax.sdk.protocol.v2.DataX/Emit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataXServer).Emit(ctx, req.(*EmitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataX_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataXServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datax.sdk.protocol.v2.DataX/GetRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataXServer).GetRequest(ctx, req.(*GetRequestOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataX_ReplyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataXServer).ReplyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datax.sdk.protocol.v2.DataX/ReplyRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataXServer).ReplyRequest(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataX_SubmitRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataXServer).SubmitRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datax.sdk.protocol.v2.DataX/SubmitRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataXServer).SubmitRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DataX_ServiceDesc is the grpc.ServiceDesc for DataX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datax.sdk.protocol.v2.DataX",
	HandlerType: (*DataXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _DataX_Initialize_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _DataX_Next_Handler,
		},
		{
			MethodName: "Emit",
			Handler:    _DataX_Emit_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _DataX_GetRequest_Handler,
		},
		{
			MethodName: "ReplyRequest",
			Handler:    _DataX_ReplyRequest_Handler,
		},
		{
			MethodName: "SubmitRequest",
			Handler:    _DataX_SubmitRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/datax-sdk-protocol.proto",
}
