// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.12
// source: v2/datax-sdk-protocol.proto

package v2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_datax_sdk_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_v2_datax_sdk_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_v2_datax_sdk_protocol_proto_rawDescGZIP(), []int{0}
}

type Initialization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Initialization) Reset() {
	*x = Initialization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_datax_sdk_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Initialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialization) ProtoMessage() {}

func (x *Initialization) ProtoReflect() protoreflect.Message {
	mi := &file_v2_datax_sdk_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialization.ProtoReflect.Descriptor instead.
func (*Initialization) Descriptor() ([]byte, []int) {
	return file_v2_datax_sdk_protocol_proto_rawDescGZIP(), []int{1}
}

type NextOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NextOptions) Reset() {
	*x = NextOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_datax_sdk_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextOptions) ProtoMessage() {}

func (x *NextOptions) ProtoReflect() protoreflect.Message {
	mi := &file_v2_datax_sdk_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextOptions.ProtoReflect.Descriptor instead.
func (*NextOptions) Descriptor() ([]byte, []int) {
	return file_v2_datax_sdk_protocol_proto_rawDescGZIP(), []int{2}
}

type NextMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Stream    string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NextMessage) Reset() {
	*x = NextMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_datax_sdk_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextMessage) ProtoMessage() {}

func (x *NextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v2_datax_sdk_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextMessage.ProtoReflect.Descriptor instead.
func (*NextMessage) Descriptor() ([]byte, []int) {
	return file_v2_datax_sdk_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *NextMessage) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *NextMessage) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *NextMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EmitMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Reference string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *EmitMessage) Reset() {
	*x = EmitMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_datax_sdk_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitMessage) ProtoMessage() {}

func (x *EmitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v2_datax_sdk_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitMessage.ProtoReflect.Descriptor instead.
func (*EmitMessage) Descriptor() ([]byte, []int) {
	return file_v2_datax_sdk_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *EmitMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmitMessage) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type EmitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmitResult) Reset() {
	*x = EmitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_datax_sdk_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResult) ProtoMessage() {}

func (x *EmitResult) ProtoReflect() protoreflect.Message {
	mi := &file_v2_datax_sdk_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResult.ProtoReflect.Descriptor instead.
func (*EmitResult) Descriptor() ([]byte, []int) {
	return file_v2_datax_sdk_protocol_proto_rawDescGZIP(), []int{5}
}

var File_v2_datax_sdk_protocol_proto protoreflect.FileDescriptor

var file_v2_datax_sdk_protocol_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x32, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64,
	0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x76, 0x32, 0x22, 0x0a, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x57, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x0b, 0x45, 0x6d,
	0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x45,
	0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x82, 0x02, 0x0a, 0x05, 0x44, 0x61,
	0x74, 0x61, 0x58, 0x12, 0x56, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x12, 0x1f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x1a, 0x25, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x04, 0x4e,
	0x65, 0x78, 0x74, 0x12, 0x22, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x78, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x22, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e,
	0x4e, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a,
	0x04, 0x45, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x6d,
	0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x21, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x78, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76,
	0x32, 0x2e, 0x45, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6c, 0x61,
	0x2d, 0x69, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x78, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_datax_sdk_protocol_proto_rawDescOnce sync.Once
	file_v2_datax_sdk_protocol_proto_rawDescData = file_v2_datax_sdk_protocol_proto_rawDesc
)

func file_v2_datax_sdk_protocol_proto_rawDescGZIP() []byte {
	file_v2_datax_sdk_protocol_proto_rawDescOnce.Do(func() {
		file_v2_datax_sdk_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_datax_sdk_protocol_proto_rawDescData)
	})
	return file_v2_datax_sdk_protocol_proto_rawDescData
}

var file_v2_datax_sdk_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v2_datax_sdk_protocol_proto_goTypes = []interface{}{
	(*Settings)(nil),       // 0: datax.sdk.protocol.v2.Settings
	(*Initialization)(nil), // 1: datax.sdk.protocol.v2.Initialization
	(*NextOptions)(nil),    // 2: datax.sdk.protocol.v2.NextOptions
	(*NextMessage)(nil),    // 3: datax.sdk.protocol.v2.NextMessage
	(*EmitMessage)(nil),    // 4: datax.sdk.protocol.v2.EmitMessage
	(*EmitResult)(nil),     // 5: datax.sdk.protocol.v2.EmitResult
}
var file_v2_datax_sdk_protocol_proto_depIdxs = []int32{
	0, // 0: datax.sdk.protocol.v2.DataX.Initialize:input_type -> datax.sdk.protocol.v2.Settings
	2, // 1: datax.sdk.protocol.v2.DataX.Next:input_type -> datax.sdk.protocol.v2.NextOptions
	4, // 2: datax.sdk.protocol.v2.DataX.Emit:input_type -> datax.sdk.protocol.v2.EmitMessage
	1, // 3: datax.sdk.protocol.v2.DataX.Initialize:output_type -> datax.sdk.protocol.v2.Initialization
	3, // 4: datax.sdk.protocol.v2.DataX.Next:output_type -> datax.sdk.protocol.v2.NextMessage
	5, // 5: datax.sdk.protocol.v2.DataX.Emit:output_type -> datax.sdk.protocol.v2.EmitResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_datax_sdk_protocol_proto_init() }
func file_v2_datax_sdk_protocol_proto_init() {
	if File_v2_datax_sdk_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v2_datax_sdk_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_datax_sdk_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Initialization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_datax_sdk_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_datax_sdk_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_datax_sdk_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_datax_sdk_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_datax_sdk_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_datax_sdk_protocol_proto_goTypes,
		DependencyIndexes: file_v2_datax_sdk_protocol_proto_depIdxs,
		MessageInfos:      file_v2_datax_sdk_protocol_proto_msgTypes,
	}.Build()
	File_v2_datax_sdk_protocol_proto = out.File
	file_v2_datax_sdk_protocol_proto_rawDesc = nil
	file_v2_datax_sdk_protocol_proto_goTypes = nil
	file_v2_datax_sdk_protocol_proto_depIdxs = nil
}
